//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2 {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApp2.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Adres benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string adres {
            get {
                return ResourceManager.GetString("adres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ara benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ara {
            get {
                return ResourceManager.GetString("ara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Arkaplan Değiştir benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string arkaplandegis {
            get {
                return ResourceManager.GetString("arkaplandegis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ArkaPlan Seç benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string arkaplansec {
            get {
                return ResourceManager.GetString("arkaplansec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bölüm Listele benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string blmlist {
            get {
                return ResourceManager.GetString("blmlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bölüm benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string bolum {
            get {
                return ResourceManager.GetString("bolum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cinsiyet benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Cinsiyet {
            get {
                return ResourceManager.GetString("Cinsiyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ders ve Bölüm Islemleri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string d_b_islem {
            get {
                return ResourceManager.GetString("d_b_islem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ders benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ders {
            get {
                return ResourceManager.GetString("ders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ders veya Bölüm Düzenle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ders_blm_dznle {
            get {
                return ResourceManager.GetString("ders_blm_dznle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ders veya Bölüm Ekle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ders_blm_ekle {
            get {
                return ResourceManager.GetString("ders_blm_ekle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ders Kaydı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ders_kaydı {
            get {
                return ResourceManager.GetString("ders_kaydı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ders Listele benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string derslist {
            get {
                return ResourceManager.GetString("derslist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dosya Veri Yolu benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string dsyvriylu {
            get {
                return ResourceManager.GetString("dsyvriylu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Email benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Erkek benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string erkek {
            get {
                return ResourceManager.GetString("erkek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Final benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string final {
            get {
                return ResourceManager.GetString("final", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Geri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string geri {
            get {
                return ResourceManager.GetString("geri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Giriş benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string giris {
            get {
                return ResourceManager.GetString("giris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Güncelle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string guncelle {
            get {
                return ResourceManager.GetString("guncelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kimlik No benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string id {
            get {
                return ResourceManager.GetString("id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Id Girin benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string id_gir {
            get {
                return ResourceManager.GetString("id_gir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İsim benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string isim {
            get {
                return ResourceManager.GetString("isim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kaydet benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string kaydet {
            get {
                return ResourceManager.GetString("kaydet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kadın benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string kdn {
            get {
                return ResourceManager.GetString("kdn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kisi Bilgileri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string kisi_bilgileri {
            get {
                return ResourceManager.GetString("kisi_bilgileri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kisileri Düzenle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string kisidznle {
            get {
                return ResourceManager.GetString("kisidznle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kisileri Listele benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string kisilst {
            get {
                return ResourceManager.GetString("kisilst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kisisel Bilgilerim benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string kisisel_bilgiler {
            get {
                return ResourceManager.GetString("kisisel_bilgiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kredi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string kredi {
            get {
                return ResourceManager.GetString("kredi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kisi Islemleri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ksislm {
            get {
                return ResourceManager.GetString("ksislm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mail Adresi Girin benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string mail_adresi_gir {
            get {
                return ResourceManager.GetString("mail_adresi_gir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mail Gönder benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string mail_gonder {
            get {
                return ResourceManager.GetString("mail_gonder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not Girisi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string notgrs {
            get {
                return ResourceManager.GetString("notgrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notlar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string notlar {
            get {
                return ResourceManager.GetString("notlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Numara benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string numara {
            get {
                return ResourceManager.GetString("numara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Öğrenci benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ogr {
            get {
                return ResourceManager.GetString("ogr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ÖGRENCI GIRISI benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ogr_grs {
            get {
                return ResourceManager.GetString("ogr_grs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ogrenci Paneli benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ogrpanel {
            get {
                return ResourceManager.GetString("ogrpanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gizle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string sfr_gzl {
            get {
                return ResourceManager.GetString("sfr_gzl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Şifre benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string sifre {
            get {
                return ResourceManager.GetString("sifre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sifremi Unuttum benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string sifremiunuttum {
            get {
                return ResourceManager.GetString("sifremiunuttum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sil benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string sil {
            get {
                return ResourceManager.GetString("sil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Soyisim benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string soyisim {
            get {
                return ResourceManager.GetString("soyisim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Telefon Numarası benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string telefon {
            get {
                return ResourceManager.GetString("telefon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toplu Veri Girişi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string tplverigir {
            get {
                return ResourceManager.GetString("tplverigir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ünvan benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string unvan {
            get {
                return ResourceManager.GetString("unvan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vize benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string vize {
            get {
                return ResourceManager.GetString("vize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yeni Kayıt benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string yenikyt {
            get {
                return ResourceManager.GetString("yenikyt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yetkili benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string yntc {
            get {
                return ResourceManager.GetString("yntc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yönetici Paneli benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string yntcpanel {
            get {
                return ResourceManager.GetString("yntcpanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   YONETICI GIRISI benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ytkl_grs {
            get {
                return ResourceManager.GetString("ytkl_grs", resourceCulture);
            }
        }
    }
}
